(IN-PACKAGE #:CL-TEXTCAT)
(DEFUN ALPHA-2 (ALPHA-3)
  (CASE ALPHA-3
    ((:AAR) :AA)
    ((:ABK) :AB)
    ((:AFR) :AF)
    ((:AKA) :AK)
    ((:AMH) :AM)
    ((:ARA) :AR)
    ((:ARG) :AN)
    ((:ASM) :AS)
    ((:AVA) :AV)
    ((:AVE) :AE)
    ((:AYM) :AY)
    ((:AZE) :AZ)
    ((:BAK) :BA)
    ((:BAM) :BM)
    ((:BEL) :BE)
    ((:BEN) :BN)
    ((:BIH) :BH)
    ((:BIS) :BI)
    ((:BOS) :BS)
    ((:BRE) :BR)
    ((:BUL) :BG)
    ((:CAT) :CA)
    ((:CHA) :CH)
    ((:CHE) :CE)
    ((:CHU) :CU)
    ((:CHV) :CV)
    ((:COR) :KW)
    ((:COS) :CO)
    ((:CRE) :CR)
    ((:CZE :CES) :CS)
    ((:DAN) :DA)
    ((:DIV) :DV)
    ((:DZO) :DZ)
    ((:ENG) :EN)
    ((:EPO) :EO)
    ((:EST) :ET)
    ((:BAQ :EUS) :EU)
    ((:EWE) :EE)
    ((:FAO) :FO)
    ((:FIJ) :FJ)
    ((:FIN) :FI)
    ((:FRE :FRA) :FR)
    ((:FRY) :FY)
    ((:FUL) :FF)
    ((:GER :DEU) :DE)
    ((:GLA) :GD)
    ((:GLE) :GA)
    ((:GLG) :GL)
    ((:GLV) :GV)
    ((:GRE :ELL) :EL)
    ((:GRN) :GN)
    ((:GUJ) :GU)
    ((:HAT) :HT)
    ((:HAU) :HA)
    ((:HEB) :HE)
    ((:HER) :HZ)
    ((:HIN) :HI)
    ((:HMO) :HO)
    ((:HRV) :HR)
    ((:HUN) :HU)
    ((:ARM :HYE) :HY)
    ((:IBO) :IG)
    ((:IDO) :IO)
    ((:III) :II)
    ((:IKU) :IU)
    ((:ILE) :IE)
    ((:INA) :IA)
    ((:IND) :ID)
    ((:IPK) :IK)
    ((:ICE :ISL) :IS)
    ((:ITA) :IT)
    ((:JAV) :JV)
    ((:JPN) :JA)
    ((:KAL) :KL)
    ((:KAN) :KN)
    ((:KAS) :KS)
    ((:GEO :KAT) :KA)
    ((:KAU) :KR)
    ((:KAZ) :KK)
    ((:KHM) :KM)
    ((:KIK) :KI)
    ((:KIN) :RW)
    ((:KIR) :KY)
    ((:KOM) :KV)
    ((:KON) :KG)
    ((:KOR) :KO)
    ((:KUA) :KJ)
    ((:KUR) :KU)
    ((:LAO) :LO)
    ((:LAT) :LA)
    ((:LAV) :LV)
    ((:LIM) :LI)
    ((:LIN) :LN)
    ((:LIT) :LT)
    ((:LTZ) :LB)
    ((:LUB) :LU)
    ((:LUG) :LG)
    ((:MAH) :MH)
    ((:MAL) :ML)
    ((:MAR) :MR)
    ((:MAC :MKD) :MK)
    ((:MLG) :MG)
    ((:MLT) :MT)
    ((:MON) :MN)
    ((:MAO :MRI) :MI)
    ((:MAY :MSA) :MS)
    ((:BUR :MYA) :MY)
    ((:NAU) :NA)
    ((:NAV) :NV)
    ((:NBL) :NR)
    ((:NDE) :ND)
    ((:NDO) :NG)
    ((:NEP) :NE)
    ((:DUT :NLD) :NL)
    ((:NNO) :NN)
    ((:NOB) :NB)
    ((:NOR) :NO)
    ((:NYA) :NY)
    ((:OCI) :OC)
    ((:OJI) :OJ)
    ((:ORI) :OR)
    ((:ORM) :OM)
    ((:OSS) :OS)
    ((:PAN) :PA)
    ((:PER :FAS) :FA)
    ((:PLI) :PI)
    ((:POL) :PL)
    ((:POR) :PT)
    ((:PUS) :PS)
    ((:QUE) :QU)
    ((:ROH) :RM)
    ((:RUM :RON) :RO)
    ((:RUN) :RN)
    ((:RUS) :RU)
    ((:SAG) :SG)
    ((:SAN) :SA)
    ((:SIN) :SI)
    ((:SLO :SLK) :SK)
    ((:SLV) :SL)
    ((:SME) :SE)
    ((:SMO) :SM)
    ((:SNA) :SN)
    ((:SND) :SD)
    ((:SOM) :SO)
    ((:SOT) :ST)
    ((:SPA) :ES)
    ((:ALB :SQI) :SQ)
    ((:SRD) :SC)
    ((:SRP) :SR)
    ((:SSW) :SS)
    ((:SUN) :SU)
    ((:SWA) :SW)
    ((:SWE) :SV)
    ((:TAH) :TY)
    ((:TAM) :TA)
    ((:TAT) :TT)
    ((:TEL) :TE)
    ((:TGK) :TG)
    ((:TGL) :TL)
    ((:THA) :TH)
    ((:TIB :BOD) :BO)
    ((:TIR) :TI)
    ((:TON) :TO)
    ((:TSN) :TN)
    ((:TSO) :TS)
    ((:TUK) :TK)
    ((:TUR) :TR)
    ((:TWI) :TW)
    ((:UIG) :UG)
    ((:UKR) :UK)
    ((:URD) :UR)
    ((:UZB) :UZ)
    ((:VEN) :VE)
    ((:VIE) :VI)
    ((:VOL) :VO)
    ((:WEL :CYM) :CY)
    ((:WLN) :WA)
    ((:WOL) :WO)
    ((:XHO) :XH)
    ((:YID) :YI)
    ((:YOR) :YO)
    ((:ZHA) :ZA)
    ((:CHI :ZHO) :ZH)
    ((:ZUL) :ZU)
    (T ALPHA-3)))